name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Inject API Key and Build
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          # Replace the placeholder in your HTML file with the actual API key
          sed -i 's/REPLACE_WITH_API_KEY/${API_KEY}/' index.html
          # Deploy to GitHub Pages
          npm install -g gh-pages
          gh-pages -d .
