name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Inject API Key
        env:
          API_KEY: ${{secrets.API_KEY}}
        run: |
          # Ensure the index.html file exists
          if [ ! -f index.html ]; then
            echo "index.html file not found!"
            exit 1
          fi

          # Replace the placeholder in your HTML file with the actual API key
          sed -i 's/REPLACE_WITH_API_KEY/API_KEY/' index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
