name: Update Incident Date

on: [push]

jobs:
  update-date:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run script
      env:
        API_KEY: ${{ secrets.API }}
      run: |
        echo "API Key is $API_KEY"
